Phase2 resources
CiscoDevNet/terraform-provider-dcnm pull request #51
Opened 2021-09-08 14:34 UTC by RutvikS-crest

Added following resources:
- dcnm_service_node
- dcnm_policy
- dcnm_template
- vrf_lite (dcnm_vrf)
- dcnm_route_peering
- dcnm_service_policy

2021-09-13 17:33 UTC, lhercot commented
Why did we remove the .github directory?

2021-09-13 17:45 UTC, RutvikS-crest commented
this must be a mistake from my end added .github back.

2021-11-19 10:29 UTC, lhercot requested changes

2021-12-17 01:39 UTC, lhercot approved these changes
LGTM

2021-12-17 01:39 UTC, merged