Policy destroy issue
CiscoDevNet/terraform-provider-dcnm pull request #85
Opened 2022-05-18 15:53 UTC by RutvikS-crest

2022-07-18 18:02 UTC, YazhRajesh commented
This is working now. Thank you!

2022-07-20 20:11 UTC, lhercot requested changes

2022-07-20 20:11 UTC, lhercot commented on dcnm/resource_dcnm_policy.go
> +		log.Println(cont.String())
Do we need the condition? Do we need the print without a context?

2022-07-20 20:11 UTC, lhercot commented on dcnm/resource_dcnm_policy.go
> +	policy.PolicyId = "POLICY-" + d.Id()
can we define a constant for "POLICY-" and use that everywhere we use it?

2022-07-20 20:11 UTC, lhercot commented on dcnm/resource_dcnm_inventory.go
> +var switchDeployMutexMap = make(map[string]*sync.Mutex, 0)
This is only used in resource_dcnm_policy it might be better to define it there and not in another file that do not use it.

2022-07-20 20:11 UTC, lhercot commented on dcnm/resource_dcnm_policy.go
> +	err := deploySwitchFabric(dcnmClient, serialNumber)
We should add a debug log that we are deploying a specific switch. We can add the log here or in the deploySwitchFabric function.

2022-07-20 20:11 UTC, lhercot commented on vendor/github.com/ciscoecosystem/dcnm-go-client/client/client.go
> +	log.Printf("[DEBUG] \n--[ HTTP Response ]----------------------------------- \n %s\n---------------------------------------------\n", string(respDump))
This will print to the log all HTTP Request including the login / authentication payload. Can we avoid that?

2022-07-20 20:11 UTC, lhercot commented on vendor/github.com/ciscoecosystem/dcnm-go-client/client/client.go
> +	log.Printf("[DEBUG] \n--[ HTTP Response ]----------------------------------- \n %s\n---------------------------------------------\n", string(respDump))
The ACI go client uses a variable (skipPayload...) to avoid printing the payload when using the login/authentication method.

2022-07-27 23:34 UTC, lhercot requested changes

2022-07-27 23:34 UTC, lhercot commented on dcnm/resource_dcnm_inventory.go
> +func resourceDCNMInventroyUpdate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
resourceDCNMInventroyUpdate -> resourceDCNMInventoryUpdate

2022-07-27 23:34 UTC, lhercot commented on dcnm/resource_dcnm_inventory.go
> +func resourceDCNMInventroyRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
resourceDCNMInventroyRead -> resourceDCNMInventoryRead

2022-07-27 23:34 UTC, lhercot commented on dcnm/resource_dcnm_inventory.go
> +func resourceDCNMInventroyDelete(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
resourceDCNMInventroyDelete -> resourceDCNMInventoryDelete

2022-07-27 23:34 UTC, lhercot commented on dcnm/resource_dcnm_inventory.go
> +func resourceDCNMInventroyCreate(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
resourceDCNMInventroyDelete -> resourceDCNMInventoryDelete

2022-07-27 23:34 UTC, lhercot commented on dcnm/resource_dcnm_inventory.go
> +				log.Printf("\nerror at updation of switch %s: %s", ip, err)
at updation -> at credential update

2022-07-27 23:34 UTC, lhercot commented on dcnm/resource_dcnm_inventory.go
> +			Summary:  fmt.Sprintf("error at switch deployment %s: %s", ip, err),
error -> Error

2022-07-27 23:34 UTC, lhercot commented on dcnm/resource_dcnm_inventory.go
> +			Summary:  fmt.Sprintf("error at switch role assignment %s: %s", ip, err),
error -> Error

2022-07-27 23:34 UTC, lhercot commented on dcnm/resource_dcnm_policy.go
> +		log.Printf("[DEBUG] error while reading policy(%s): %v", policyId, cont.String())
Why twice the same identical logs?

2022-07-27 23:34 UTC, lhercot commented on dcnm/resource_dcnm_policy.go
> +	err := deploySwitchFabric(dcnmClient, serialNumber)
Is this fixed in the parent function?

2022-07-27 23:34 UTC, lhercot commented on go.sum
> +github.com/ciscoecosystem/dcnm-go-client v0.2.6/go.mod h1:phw1JcChpnYgPjtyaael7FYGzZCHV8i6D9N4vDcEGo8=
Remove unused dcnm-go-client

2022-07-29 16:50 UTC, lhercot requested changes

2022-07-29 16:50 UTC, lhercot commented on dcnm/resource_dcnm_inventory.go
> +				log.Printf("\nerror at updation of switch %s: %s", ip, err)
not fixed, at updation -> at credential update

2022-08-03 16:05 UTC, lhercot approved these changes
LGTM

2022-08-03 16:36 UTC, merged